name: Build plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'

      - name: Build with Gradle
        run: gradle build

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: sparkwebapi-plugin
          path: build/libs/*.jar
          if-no-files-found: error

  download-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: sparkwebapi-plugin
          path: artifacts

      - name: List downloaded files
        run: ls -R
        working-directory: artifacts
